# base is Ubuntu 16.04
FROM ubuntu:16.04
MAINTAINER kurama554101 <shotasakamoto554101@gmail.com>

# Start docker file
RUN echo "now building..."

# update apt-get
RUN apt-get update --fix-missing

# setup workdir
WORKDIR /home/development/

# add install directory
ADD docker/install install/

# install core packages
RUN set -x && \
    bash install/ubuntu_install_core_packages.sh

# install Python and Pip
RUN set -x && \
    bash install/ubuntu_install_python.sh

# install Kafka
RUN set -x && \
    bash install/ubuntu_install_kafka.sh

# install Fuast
RUN set -x && \
    pip3 install -U faust, aiomonitor

# start bash
# CMD [ '/bin/bash'  ]